stages:
  - test
  - build
  - deploy

variables:
  REGISTRY_PATH: "fileshare.local:5000/${CI_PROJECT_PATH_SLUG}"

#gofmt:
#  stage: test
#  image: golang:1.16
#  tags:
#    - docker-exec
#  before_script: [] # prevent run `docker login`
#  script:
#    - test -z "$(gofmt -s -l -e -d $(find . -name '*.go' -type f -print | grep -v vendor | tr '\n' ' ') | tee /dev/stderr)"

lint:
  stage: test
  image: golangci/golangci-lint:v1.42.0
  tags:
    - docker-exec
  artifacts:
    paths:
      - lint_succeeded
  cache:
    key: torrents-watcher-golangci-lint
    paths:
      - /var/golangci-lint-cache
  before_script: [] # prevent run docker login
  variables:
    GOFLAGS: -mod=vendor
    GOLANGCI_LINT_CACHE: /var/golangci-lint-cache
  script:
    - mkdir cmd/torrentsWatcher/dist && touch cmd/torrentsWatcher/dist/dummy.txt
    - golangci-lint run -v --timeout=5m
    - touch lint_succeeded

test-go:
  stage: test
  tags:
    - docker-exec
  artifacts:
    paths:
      - test_go_succeeded
  image: golang:1.17
  before_script: [] # prevent run docker login
  variables:
    GOFLAGS: -mod=vendor
  script:
    - mkdir cmd/torrentsWatcher/dist && touch cmd/torrentsWatcher/dist/dummy.txt
    - go test ./... -v -coverprofile coverage.out
    - go tool cover -func=coverage.out
    - touch test_go_succeeded
  only:
    - branches
  except:
    - tags

test-js:
  stage: test
  tags:
    - docker-exec
  artifacts:
    paths:
      - test_js_succeeded
  cache:
    key: ${CI_PROJECT_PATH_SLUG}-test-js
  image: node:13
  before_script: [] # prevent run docker login
  script:
    - cd frontend && npm ci --dev && npm run test && cd ..
    - touch test_js_succeeded

build:
  stage: build
  needs:
    - lint
    - test-go
    - test-js
  artifacts:
    paths:
      - build_succeeded
  image: docker
  script:
    - if [ ! -f lint_succeeded ]; then exit 1; fi
    - if [ ! -f test_go_succeeded ]; then exit 1; fi
    - if [ ! -f test_js_succeeded ]; then exit 1; fi
    - docker build -t ${CI_PROJECT_PATH_SLUG}:latest .
#    - docker tag ${CI_PROJECT_PATH_SLUG}:latest ${REGISTRY_PATH}:latest
#    - docker push ${REGISTRY_PATH}:latest
    - touch build_succeeded
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

deploy:
  stage: deploy
  needs:
    - build
  image: docker
  script:
    - if [ ! -f build_succeeded ]; then exit 1; fi
    - docker stop ${CI_PROJECT_PATH_SLUG} && docker rm ${CI_PROJECT_PATH_SLUG} || true
    - >
      docker run -d --name ${CI_PROJECT_PATH_SLUG}
      --volume /var/${CI_PROJECT_PATH_SLUG}/torrents.db:/torrents.db
      --volume /var/${CI_PROJECT_PATH_SLUG}/config.yml:/config.yml
      --volume ${DOWNLOADS_DIR}:/downloads
      -p ${PORT_HTTP}:1000
      -p ${PORT_GRPC}:1001
      -e PORT_GRPC=${PORT_GRPC}
      --restart=always
      ${CI_PROJECT_PATH_SLUG}:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always