// source: torrentsList.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var torrent_pb = require('./torrent_pb.js');
goog.object.extend(proto, torrent_pb);
goog.exportSymbol('proto.protobuf.Torrents', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protobuf.Torrents = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.protobuf.Torrents.repeatedFields_, null);
};
goog.inherits(proto.protobuf.Torrents, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protobuf.Torrents.displayName = 'proto.protobuf.Torrents';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.protobuf.Torrents.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protobuf.Torrents.prototype.toObject = function(opt_includeInstance) {
  return proto.protobuf.Torrents.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protobuf.Torrents} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuf.Torrents.toObject = function(includeInstance, msg) {
  var f, obj = {
    torrentsList: jspb.Message.toObjectList(msg.getTorrentsList(),
    torrent_pb.Torrent.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protobuf.Torrents}
 */
proto.protobuf.Torrents.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protobuf.Torrents;
  return proto.protobuf.Torrents.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protobuf.Torrents} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protobuf.Torrents}
 */
proto.protobuf.Torrents.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new torrent_pb.Torrent;
      reader.readMessage(value,torrent_pb.Torrent.deserializeBinaryFromReader);
      msg.addTorrents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protobuf.Torrents.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protobuf.Torrents.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protobuf.Torrents} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuf.Torrents.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTorrentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      torrent_pb.Torrent.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Torrent torrents = 1;
 * @return {!Array<!proto.protobuf.Torrent>}
 */
proto.protobuf.Torrents.prototype.getTorrentsList = function() {
  return /** @type{!Array<!proto.protobuf.Torrent>} */ (
    jspb.Message.getRepeatedWrapperField(this, torrent_pb.Torrent, 1));
};


/**
 * @param {!Array<!proto.protobuf.Torrent>} value
 * @return {!proto.protobuf.Torrents} returns this
*/
proto.protobuf.Torrents.prototype.setTorrentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.protobuf.Torrent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.protobuf.Torrent}
 */
proto.protobuf.Torrents.prototype.addTorrents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.protobuf.Torrent, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.protobuf.Torrents} returns this
 */
proto.protobuf.Torrents.prototype.clearTorrentsList = function() {
  return this.setTorrentsList([]);
};


goog.object.extend(exports, proto.protobuf);
